### PR TITLE
Improved extension install instructions for lab vs. notebook

### PR DESCRIPTION
**Pull request by ataiya**
Resolves Issue #267

### CODE REVIEW

**Comment by stonebig** [comment]
I maybe wrong, but isn't pythreejs included per default in Jupyterlab-1.0.0.rc1 ?

**Comment by vidartf** [comment]
I think you are mistaken. Pythreejs is not distributed with jupyterlab, and I don't think it ever has been.

**Comment by stonebig** [comment]
will retry with latest jupyterlab

**Comment by vidartf** [comment]
Pythreejs hasn't been ported to lab 1.0 yet, hoping to get it done by the end of the week.

**Comment by stonebig** [comment]
image

**Comment by vidartf** [comment]
I just released 2.1.1 earlier today 😄

**Comment by ataiya** [comment]
@vidartf did you make any tests regarding whether it works under jupyter lab?

**Pull request merged**
